language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker images # print all images building
  - docker tag reverseproxy thomasdevs/reverseproxy:v1
  - docker tag udagram-api-user thomasdevs/udagram-api-user:v1
  - docker tag udagram-api-feed thomasdevs/udagram-api-feed:v1
  - docker tag udagram-frontend:local thomasdevs/udagram-frontend:v1
  - echo "all images builded successfully"


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thomasdevs/reverseproxy:v1
  - docker push thomasdevs/udagram-api-user:v1
  - docker push thomasdevs/udagram-api-feed:v1
  - docker push thomasdevs/udagram-frontend:v1
  - echo "all images pushed to dockerhub successfully"