apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      app: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: thomasdevs/udagram-api-user:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 300m
            memory: 1100Mi
          requests:
            cpu: 100m
            memory: 100Mi